---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-diplom
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: my-first-registry
        image: cr.yandex/crpmh7guhbh8fj5qs00k/komlev_webapp
        imagePullPolicy: "Always"  
        ports:
        - containerPort: 80
      imagePullSecrets: [{ name: 'basson63' }]

