---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-diplom
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-diplom-6bfd65db77-484cf
        image: cr.yandex/crpmh7guhbh8fj5qs00k/komlev_webapp
        ports:
        - containerPort: 80
